### ISSUE TITLE
Can't import books "o.at is not a function"

### ISSUE THREAD

**Issue by skyspiral** [lrorpilla/jidoujisho#153]
Tested on 2.3.7. Trying to import any epub in the embedded ebook reader returns a `Bookimport failed o.at is not a function` message.
Tested on the native https://reader.ttsu.app page and uploading the same epub works there.

![image](https://user-images.githubusercontent.com/8377977/217700501-131fe3ab-9172-46b5-a136-4b59a87d9dc6.png)

**Comment by lrorpilla** [comment]
Could you give me more details on your device? This seems to be an issue involving poly-fills. I can probably make a new build which includes a fix, but I'll need some testing on your end to confirm it works.

**Comment by lrorpilla** [comment]
This build includes a work in progress 2.4.0 (only supporting Japanese at the moment) that includes an overhaul of the dictionary system and should be much, much faster than the current system, supports wildcard searching (? or ？ for one character, * or ※ (こめ) for zero to any characters) but will require a fresh installation. You can get the build **[here](https://drive.google.com/file/d/1q0drLYf1V7U52yQfmCOoLkR2QL2ou0jO/view?usp=share_link)**. 

Again, I can't confirm the fix as it is specific to your device/WebView version so let me know if ever you have any more issues.

**Comment by lrorpilla** [comment]
Changes for this issue have been included in the [**2.4 preview**](https://github.com/lrorpilla/jidoujisho/releases/tag/2.4-preview).

**Comment by skyspiral** [comment]
@lrorpilla I found the issue, it was my WebView version. For reference I was using Android System Webview 81.0.4044.138 and Android 10. I updated it and could no longer reproduce the issue (using the 2.4.0 build). Thanks for the pointer.
